// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqE1-R4bwITECCVK3S6FdSV_yOAzYdoms',
    appId: '1:187110141097:web:256fb7bf7a575ebe1c4db8',
    messagingSenderId: '187110141097',
    projectId: 'demoapp-631f7',
    authDomain: 'demoapp-631f7.firebaseapp.com',
    storageBucket: 'demoapp-631f7.firebasestorage.app',
    measurementId: 'G-9VJ5MEJW66',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARbzIv01XRzcTOHDJ6eDA63IPAS6mh4P4',
    appId: '1:187110141097:android:e1ec9f1383d93df31c4db8',
    messagingSenderId: '187110141097',
    projectId: 'demoapp-631f7',
    storageBucket: 'demoapp-631f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA59zenc9iD3uzxdcqwJqPeX4mqk8vVoOY',
    appId: '1:187110141097:ios:2ee3cec781dc2a331c4db8',
    messagingSenderId: '187110141097',
    projectId: 'demoapp-631f7',
    storageBucket: 'demoapp-631f7.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA59zenc9iD3uzxdcqwJqPeX4mqk8vVoOY',
    appId: '1:187110141097:ios:2ee3cec781dc2a331c4db8',
    messagingSenderId: '187110141097',
    projectId: 'demoapp-631f7',
    storageBucket: 'demoapp-631f7.firebasestorage.app',
    iosBundleId: 'com.example.demoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqE1-R4bwITECCVK3S6FdSV_yOAzYdoms',
    appId: '1:187110141097:web:c273dd00dc7852de1c4db8',
    messagingSenderId: '187110141097',
    projectId: 'demoapp-631f7',
    authDomain: 'demoapp-631f7.firebaseapp.com',
    storageBucket: 'demoapp-631f7.firebasestorage.app',
    measurementId: 'G-SPC5PX5VHH',
  );
}
